name: Deploy Database Helm Chart to AKS

on:
  workflow_dispatch:  # Manually trigger the workflow
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        install_kubectl: true
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'
    - name: Configure kubectl
      run: mkdir -p $HOME/.kube && touch $HOME/.kube/config
      run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
    - name: Install Helm chart
      run: helm install my-release-${{ github.run_number }} ./k8s-helm-scripts/helm-database/database-deploy
